name: Minify and Update

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  minify-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Auto-increment version in code.js
      run: |
        # Expect first line like: const version = "12.06";
        version=$(sed -n '1s/.*const version = "\([0-9]\+\)\.\([0-9]\+\)".*/\1.\2/p' code.js)
        if [ -z "$version" ]; then
          echo "Could not parse version from code.js first line"; exit 1
        fi

        major=${version%%.*}
        minor=${version#*.}

        # Force base-10 to avoid octal interpretation
        major=$((10#$major))
        minor=$((10#$minor))

        if [ "$minor" -ge 99 ]; then
          major=$((major+1))
          minor=0
        else
          minor=$((minor+1))
        fi

        new_version=$(printf "%d.%02d" "$major" "$minor")

        # Replace the first line with the new version
        sed -i '1s|^.*$|const version = "'"$new_version"'";|' code.js

        echo "NEW_VERSION=$new_version" >> "$GITHUB_ENV"
        echo "Bumped version to $new_version"


    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'   # keep as-is; bump if your deps need >=20

    - name: Install dependencies
      run: npm install

    - name: Build minified code (temp only)
      run: npx uglify-js code.js -o code.min.js

    - name: Update bm-toolkit-desktop.user.js (inject code + bump @version)
      run: |
        test -f bm-toolkit-desktop.user.js || { echo "bm-toolkit-desktop.user.js not found"; exit 1; }

        # 1) Inject minified code at line 16 (preserves your header with namespace/URLs)
        tmp_file=$(mktemp)
        cp code.min.js "$tmp_file"
        sed -i '16s~.*~'"$(sed 's/[\/&]/\\&/g' "$tmp_file")"'~' bm-toolkit-desktop.user.js
        rm "$tmp_file"

        # 2) Bump @version in the header (assumes it's on line 4)
        sed -i "4s|// @version .*|// @version $NEW_VERSION|" bm-toolkit-desktop.user.js

        # Cleanup: we don't commit code.min.js
        rm -f code.min.js

    - name: Detect changes
      id: changes
      run: |
        git add code.js bm-toolkit-desktop.user.js
        if git diff --cached --quiet; then
          echo "changed=false" >> "$GITHUB_OUTPUT"
          echo "No changes detected."
        else
          echo "changed=true" >> "$GITHUB_OUTPUT"
          echo "Changes detected."
        fi

    - name: Commit and push changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -m "Build .user.js and bump to v$NEW_VERSION"
        git push
